name: Steep
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.steep.app
    DEVELOPMENT_TEAM: K4B3QDXWLD
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SWIFT_VERSION: 5.10
    TARGETED_DEVICE_FAMILY: 1
    INFOPLIST_FILE: Info.plist
packages: {}
targets:
  Steep:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Components
      - path: Design
      - path: Features
      - path: Models
      - path: Services
      - path: Utilities
      - path: Info.plist
      - path: LaunchScreen.storyboard
      - path: Assets.xcassets
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: Info.plist

  SteepTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Steep
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.steep.app.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Steep.app/Steep
        BUNDLE_LOADER: $(TEST_HOST)
