name: SipMVP
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.rajanchavada.sip
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SWIFT_VERSION: 5.10
    TARGETED_DEVICE_FAMILY: 1
    INFOPLIST_FILE: Info.plist
packages: {}
targets:
  SipMVP:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Components
      - path: Design
      - path: Features
      - path: Models
      - path: Services
      - path: Utilities
      - path: Info.plist
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: Info.plist

  SipMVPTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: SipMVP
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sip.app.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/SipMVP.app/SipMVP
        BUNDLE_LOADER: $(TEST_HOST)
